steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--build-arg",
        "BUILDKIT_INLINE_CACHE=1",
        "-t",
        "us-west1-docker.pkg.dev/$PROJECT_ID/knowledge-assistant/app:$SHORT_SHA",
        ".",
      ]

  # Push the container image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-west1-docker.pkg.dev/$PROJECT_ID/knowledge-assistant/app:$SHORT_SHA",
      ]

  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "internal-knowledge-assistant"
      - "--image"
      - "us-west1-docker.pkg.dev/$PROJECT_ID/knowledge-assistant/app:$SHORT_SHA"
      - "--region"
      - "us-west1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--service-account"
      - "knowledge-assistant-runner@$PROJECT_ID.iam.gserviceaccount.com"
      - "--set-env-vars"
      - "FLASK_CONFIG=production,APP_SECRETS_PATH=/secrets/app/secrets.json"
      - "--update-secrets"
      - "/secrets/app/secrets.json=app-secrets:latest"

images:
  - "us-west1-docker.pkg.dev/$PROJECT_ID/knowledge-assistant/app:$SHORT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY
